plugins:
  - jekyll-minifier

collections:
  sites:
    output: false
  jobs:
    output: false
  pages:
    output: true
    permalink: /:name/

jekyll-minifier:
    exclude: 'game/*'

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - README.md
  - LICENSE
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - shell.nix
  - default.nix
